version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "70:a5:b6:95:53:c0:69:ca:b5:cd:68:6d:cf:3e:6f:dc"
      - run:
          name: Copy updated files to VM
          command: scp -o StrictHostKeyChecking=no -r ./* azureuser@40.85.160.101:~/myapp

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh azureuser@40.85.160.101 "cd myapp && sudo npm run-script stop && npm install && sudo npm start"

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: main # only deploy on the main branch
